security:
  oauth2:
    client:
      registration:
        kakao:
          clientId: d383377007505bd2bc2bd5771610d8f8

custom:
  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890